[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Optional: enable pretty URLs (Astro already outputs index.html per route)
# [[redirects]]
#   from = "/index.html"
#   to = "/"
#   status = 200

